In [1]:
import numpy as np

# LeetCode: Easy

https://leetcode.com/problemset/algorithms/

In [2]:
s = 'hello'
t = 'loleh'

In [3]:
sorted(s) == sorted(t)

True

# 100+ exercises: Level 1

https://github.com/zhiwehu/Python-programming-exercises/blob/master/100%2B%20Python%20challenging%20programming%20exercises.txt

In [4]:
print ','.join([str(i) for i in range(200, 3201, 7) if i%5>0])

207,214,221,228,242,249,256,263,277,284,291,298,312,319,326,333,347,354,361,368,382,389,396,403,417,424,431,438,452,459,466,473,487,494,501,508,522,529,536,543,557,564,571,578,592,599,606,613,627,634,641,648,662,669,676,683,697,704,711,718,732,739,746,753,767,774,781,788,802,809,816,823,837,844,851,858,872,879,886,893,907,914,921,928,942,949,956,963,977,984,991,998,1012,1019,1026,1033,1047,1054,1061,1068,1082,1089,1096,1103,1117,1124,1131,1138,1152,1159,1166,1173,1187,1194,1201,1208,1222,1229,1236,1243,1257,1264,1271,1278,1292,1299,1306,1313,1327,1334,1341,1348,1362,1369,1376,1383,1397,1404,1411,1418,1432,1439,1446,1453,1467,1474,1481,1488,1502,1509,1516,1523,1537,1544,1551,1558,1572,1579,1586,1593,1607,1614,1621,1628,1642,1649,1656,1663,1677,1684,1691,1698,1712,1719,1726,1733,1747,1754,1761,1768,1782,1789,1796,1803,1817,1824,1831,1838,1852,1859,1866,1873,1887,1894,1901,1908,1922,1929,1936,1943,1957,1964,1971,1978,1992,1999,2006,2013,2027,2034,2041,2048,2062,2069,2076,2083,2097,2104,21

In [5]:
def factorial(x):
    res = 1
    for i in range(1,x+1):
        res *= i
    return res

In [6]:
factorial(8)

40320

In [7]:
def dict_of_squares(x):
    res = {}
    for i in range(1,x+1):
        res[i] = i**2
    return res

In [8]:
print dict_of_squares(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [9]:
s = '34,67,55,33,12,98'

In [10]:
list(s.split(','))

['34', '67', '55', '33', '12', '98']

In [11]:
tuple(s.split(','))

('34', '67', '55', '33', '12', '98')

##### #----------------------------------------# Question 5 Level 1  Question: Define a class which has at least two methods: getString: to get a string from console input printString: to print the string in upper case. Also please include simple test function to test the class methods.

# 100+ exercises: Level 2

In [12]:
def use_formula(x):
    C = 50.
    H = 30.
    
    Q = int(np.sqrt((2.*C*x)/H))
    
    return str(Q)

D = '100,150,180'
output = []
for val in D.split(','):
    output.append(use_formula(float(val)))
    
print ','.join(output)

18,22,24


In [13]:
s = '3,5'
X, Y = [int(i) for i in s.split(',')]

# first pass:
prod_array = np.empty([X, Y])

for i in range(X):
    for j in range(Y):
        prod_array[i,j] = i*j
        
print prod_array

# better way:
prod_array = np.arange(X)[:,np.newaxis].astype(float) * np.arange(Y)[np.newaxis,:].astype(float)
print prod_array

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]]


In [14]:
s = 'without,hello,bag,world'.split(',')
s.sort()

In [15]:
print ','.join(s)

bag,hello,without,world


In [16]:
s = 'hello world and practice makes perfect and hello world again'

In [17]:
l = sorted(s.split(' '))

In [18]:
# manual method:
u = []
for w in l:
    if w not in u:
        u.append(w)
        
# built-in method:
u = sorted(list(set(l)))

In [19]:
print ' '.join(u)

again and hello makes perfect practice world


# McDowell Ch. 17

In [20]:
# easy but probably slow way
def fact(n):
    res = 1
    for i in range(1,n+1):
        res *= i
    return res

def num_zeros(n):
    n_fact = fact(n)
    
    num_zeros = 0
    s = str(n_fact)
    
    for i in range(len(s)):
        if s[len(s)-i-1] == '0':
            num_zeros += 1
        else:
            break
    return num_zeros

In [21]:
print str(fact(200)) + ': ' + str(num_zeros(200))

788657867364790503552363213932185062295135977687173263294742533244359449963403342920304284011984623904177212138919638830257642790242637105061926624952829931113462857270763317237396988943922445621451664240254033291864131227428294853277524242407573903240321257405579568660226031904170324062351700858796178922222789623703897374720000000000000000000000000000000000000000000000000: 49


# Miller & Ranum

### Create helper functions

In [22]:
# recursive version
def gcd(n,m):
    # set m to be the larger (or equal)
    if m < n:
        m, n = (n, m)
    
    # find remainder of m / n
    newn = m % n

    # if n goes into m evenly, GCD is just n
    if newn == 0:
        return n
    
    # if n does not divide into m evenly, GCD is GCD of n and m % n
    else:
        return gcd(newn,n)

# iterative version
def gcd(n,m):
    # set m to be the larger (or equal)
    if m < n:
        m, n = (n, m)
    
    # find remainder of m / n
    newn = m % n

    # if n goes into m evenly, GCD is just n
    if newn == 0:
        return n

    # make n and m smaller until n divides into m
    while m % n != 0:
        newn = m % n
        m = n
        n = newn

    # n has now reached the GCD
    return n
    

### Define fraction class

In [25]:
class Fraction:
    def __init__(self,top,bottom):
        self.num = top
        self.den = bottom

    def show(self):
        print str(self.num) + '/' + str(self.den)

    def __str__(self):
        return str(self.num) + '/' + str(self.den)

    def __add__(self,other):
        newnum = self.num*other.den + other.num*self.den
        newden = self.den*other.den

        factor = gcd(newnum, newden)

        return Fraction(newnum/factor,newden/factor)

    def __sub__(self,other):
        negative = Fraction(-other.num, other.den)
        return self.__add__(negative)

    def __mul__(self,other):
        newnum = self.num * other.num
        newden = self.den * other.den
        factor = gcd(newnum, newden)

        return Fraction(newnum/factor, newden/factor)

    def __div__(self,other):
        inverse = Fraction(other.den, other.num)
        return self.__mul__(inverse)        

    def __eq__(self,other):
        # reduce fractions if needed
        factor = gcd(self.num, self.den)
        self = Fraction(self.num/factor, self.den/factor)
        factor = gcd(other.num, other.den)
        other = Fraction(other.num/factor, other.den/factor)

        # test for equality
        return self.num == other.num and self.den == other.den

    def __lt__(self,other):
        pass


### Test fraction class definitions

In [26]:
frac = Fraction(3,5)
print frac
str(frac)

3/5


'3/5'

In [27]:
f1 = Fraction(3,10)
f2 = Fraction(2,10)
print f1+f2

1/2


In [28]:
f1 = Fraction(2,5)
f2 = Fraction(4,10)
f3 = f1
print f1 == f2
print f1 == f3

True
True


In [29]:
f1 = Fraction(3,10)
f2 = Fraction(-2,10)
print f1-f2

1/2


In [30]:
f1 = Fraction(3,10)
f2 = Fraction(2,10)
print f1*f2

3/50


In [31]:
f1 = Fraction(3,10)
f2 = Fraction(2,10)
print f1/f2

3/2


# Miscellaneous

In [33]:
age = raw_input("how old are you? ")

how old are you? 


In [34]:
l = [0,1,2]

In [35]:
def merge_sort(scrambled):
    if len(scrambled) == 1:
        return scrambled
    
    n = len(scrambled)//2
    left_half = merge_sort(scrambled[:n])
    right_half = merge_sort(scrambled[n:])
    
    counter = 0 # current location in sorted list
    while len(left_half) and len(right_half):
        if left_half[0] >= right_half[0]:
            scrambled[counter] = right_half[0]
            del right_half[0]
        else:
            scrambled[counter] = left_half[0]
            del left_half[0]
        counter += 1
    if len(left_half):
        scrambled[counter:] = left_half
    elif len(right_half):
        scrambled[counter:] = right_half
        
    return scrambled

In [36]:
print merge_sort(['1',11,'a'])

[11, '1', 'a']


In [37]:
def merge_sort(scrambled,first=0,last=None):
    if last is None:
        last = len(scrambled)

    if last-first <= 1:
        return scrambled
    
    n = first+(last-first)//2
    left_half = merge_sort(list(scrambled),first,n)
    right_half = merge_sort(list(scrambled),n,last)
    
    counter = first # current location in sorted list
    left_idx = first # current location in left_half
    right_idx = n # current location in right half
    while left_idx < n and right_idx < last:
        if left_half[left_idx] <= right_half[right_idx]:
            scrambled[counter] = left_half[left_idx]
            left_idx += 1
        else:
            scrambled[counter] = right_half[right_idx]
            right_idx += 1
        counter += 1
    if left_idx < n:
        scrambled[counter:last] = left_half[left_idx:n]
    elif right_idx < last:
        scrambled[counter:last] = right_half[right_idx:last]
    
    return scrambled

In [38]:
s = merge_sort([3,3,5,2,6,2,8,9,1])
s

[1, 2, 2, 3, 3, 5, 6, 8, 9]

In [39]:
def quick_sort(sequence,first=0,last=None):
    if last is None:
        last = len(sequence)

    if last-first <= 1:
        return sequence

    # start by using first element as pivot
    pivot = first
    
    left = first+1
    right=last-1
    while left < right:
        if sequence[left] > sequence[pivot] and sequence[right] < sequence[pivot]:
            sequence[left], sequence[right] = sequence[right], sequence[left]
            left += 1
            right -= 1
        else:
            if sequence[left] <= sequence[pivot]:
                left += 1
            if sequence[right] >= sequence[pivot]:
                right -= 1
    
    sequence[pivot], sequence[left] = sequence[left], sequence[pivot]
        

In [40]:
s[0], s[1] = s[1], s[0]

In [41]:
[None]*5

[None, None, None, None, None]